import {
  Client,
  ClientOptions,
  Intents,
  MessageEmbed,
  MessageOptions,
  MessagePayload,
  TextChannel,
} from 'discord.js';
import {
  Semaphore,
  sleep,
} from './util.service';
import { config } from '../config';
import { logMessage } from './logger.service';
import { ChannelClassEnum } from '../types/serviceDiscordTypes';

const throttleSleepTimeMs = config.meta.inDevelopment ? 5000 : 60000;

const options: ClientOptions = {
  intents: new Intents()
    .add(Intents.FLAGS.DIRECT_MESSAGES)
    .add(Intents.FLAGS.GUILDS)
    .add(Intents.FLAGS.GUILD_MESSAGES)
    .add(Intents.FLAGS.GUILD_MESSAGE_REACTIONS),
};
const client = new Client(options);

const messageQueue: MessagePayload[] = [];
const queueLock = new Semaphore(1);
const throttleMessages = async () => {
  // eslint-disable-next-line no-constant-condition
  while (true) {
    let didSomething = false;
    while (messageQueue.length > 0) {
      didSomething = true;
      logMessage(config.discord.identifier, 'draining message queue');
      // eslint-disable-next-line no-await-in-loop
      const release = await queueLock.acquire();
      const messagePayload = messageQueue.shift() as MessagePayload;
      (messagePayload.target as TextChannel).send(messagePayload);
      release();
      // eslint-disable-next-line no-await-in-loop
      await sleep(3000);
    }
    if (didSomething) {
      logMessage(config.discord.identifier, 'message queue emptied');
    }
    // eslint-disable-next-line no-await-in-loop
    await sleep(throttleSleepTimeMs);
  }
};

export const initialize = () => new Promise((resolve) => {
  client.login(config.discord.secret);
  client.on('ready', () => {
    logMessage('service.discord.initialize', `${config.discord.username} has logged in.`);
    resolve(true);
    throttleMessages();
  });
});

export const announce = async (
  channelClass: ChannelClassEnum,
  message?: string,
  embed?: MessageEmbed,
  taggedRoles: string[] = [],
) : Promise<boolean> => {
  if (message === undefined && embed === undefined) {
    return false;
  }
  const release = await queueLock.acquire();
  config.discord.servers.forEach((server) => {
    const destinationChannels = server.channels[channelClass];
    if (!destinationChannels || destinationChannels.length === 0) {
      return;
    }
    embed.setFooter({
      text: `This message was automatically generated by ${config.discord.username}`,
    }).setTimestamp();
    const messageOptions = {
      embeds: [embed],
    } as MessageOptions;
    if (taggedRoles.length > 0 || message) {
      const roleContent = taggedRoles.map((roleName) => {
        const roleId = server.roles.find((role) => role.name === roleName)?.id;
        return roleId ? `<@&${roleId}>` : '';
      }).join(' ');
      messageOptions.content = roleContent + (message || '');
    }
    destinationChannels.forEach((rawChannel) => {
      const channel = client.channels.cache.get(rawChannel.id);
      if (channel && channel.isText()) {
        messageQueue.push(new MessagePayload(
          channel,
          messageOptions,
        ));
      }
    });
  });
  release();
  return true;
};
